### ISSUE TITLE
AttributeError: 'TestScanner' object has no attribute 'runTest'

### ISSUE THREAD

**Issue by jsshafer** [baileyparker/phf-compilers-tests#20]
Team,

From a new install, I get the following error (had no issues for past projects):

<img width="995" alt="screen shot 2018-03-14 at 9 14 49 am" src="https://user-images.githubusercontent.com/5322731/37404414-340aee22-2768-11e8-8d5b-b574d7f6aae4.png">

Any ideas?

**Comment by sobeckley** [comment]
This is a known issue (which is to say we have it as well), however Bailey is currently scrambling to get a bunch of assignments (including but not limited to compilers) done, so I wouldn't expect it to get fixed before tonight.  However you can still run test cases the ol fashion way by running it yourself and diffing the results, so test case contributions are still useful :)

**Comment by jsshafer** [comment]
Got it - thanks!

**Comment by baileyparker** [comment]
Fixed this from bed, but hopefully it should work for you now!

**Comment by jsshafer** [comment]
Thanks Bailey - get better!
